version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: kutak_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: kutak_test
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content/themes/kutak/:/var/www/html/wp-content/themes/kutak/:rw
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_DATABASE: wordpress
